### ISSUE TITLE
ActiveRecord::StatementInvalid: Mysql2::Error: BLOB/TEXT column 'rank' used in key specification without a key length

### ISSUE THREAD

**Issue by brendon** [richardboehme/lexorank#9]
Well done on putting together this gem. It's something I've theorised about with others as I maintain the `acts_as_list` and `ranked-model` gems and both have their downsides. Lexical ranking is kind of like what `ranked-model` does but with more sparseness between ranks. One of the keys to limiting the amount of rebalancing is to not just go for 50% between surrounding ranks but rather have the concept of a minimum gap. If one doesn't do that in `ranked-model` land we run out of ranks and have to rebalance after 30 or so appends to the end of the list. Anyway, just something to think about. I haven't actually implemented this in `ranked-model` yet. It's a bit off topic lol! :)

I had a go at creating a migration on MySQL but got the following error:

```ActiveRecord::StatementInvalid: Mysql2::Error: BLOB/TEXT column 'rank' used in key specification without a key length```

It seems that indexing a variable length text column isn't possible in MySQL? Have you run into this on your end?

**Comment by richardboehme** [comment]
Hey thanks for looking into this gem! I think there is definitely still room for improvement on the ranking algorithm used. A minimum gap might be a first step on this. However I think it might not be as bad that we don't have that right now, because between two letters there are always a huge number of combinations until we *need* to rebalance. 

About the error: It seems like you are correct. MySQL does not allow unique text columns. I think we would need to use a varchar/string column for this then. This should still be large enough to store a lot of elements. I can have a deeper look at this next week!

**Comment by brendon** [comment]
Thanks @richardboehme :) That's true unless you're always adding new items to the end of the list. Every time a new item is added the gap gets 50% smaller. With `ranked-model` we run out of space after about 30 items are added (quite few) and then a rebalance is required. Does this happen with `lexorank`?

Having arbitrary gaps would help in this instance except that we'd want to know approximately how many records would exist inside a scope so we could optimise the gap.

In my case in the end I actually rolled my own Rails Concern: https://gist.github.com/brendon/d6cfd60cb5e70dc77a15a2476f04d279

All list operations work within a transaction and so are atomic. I use position 0 temporarily for the moved item to prevent any position collisions. Would be interesting to see how it held up under significant load.

**Comment by richardboehme** [comment]
> `ActiveRecord::StatementInvalid: Mysql2::Error: BLOB/TEXT column 'rank' used in key specification without a key length`
> 
> It seems that indexing a variable length text column isn't possible in MySQL? Have you run into this on your end?

It actually seems to work with the newest versions of MariaDB. However MySQL does not seem to like a unique index on text columns. As I said you could just use the varchar/string type instead.  I'm currently looking into adding a new column type for ranks (see #8). This would allow us to choose the correct column type dependent on the database manager used.

**Comment by brendon** [comment]
Thanks @richardboehme, I see your point re the extra width of a text based column. That certainly solves that problem!

Interesting about the support between MySQL and MariaDB. Hopefully MySQL catches up in that regard :)

I'll close this for now as it at least points people at a solution in the meantime. If I find my custom positioning concern isn't cutting it I'll take another look at `lexorank` for sure :D
